import { FirebirdReserved } from "../interfaces";
/**
 * Firebird reserved keywords
 */

export const firebirdReserved: FirebirdReserved[] = [
  { label: "ADD", detail: "Firebird reserved word", documentation: "Adds a column to a table or an element to an index." },
  { label: "ADMIN", detail: "Firebird reserved word", documentation: "Administrative privilege keyword." },
  { label: "ALL", detail: "Firebird reserved word", documentation: "Returns all rows; used with SELECT or UNION ALL." },
  { label: "ALTER", detail: "Firebird reserved word", documentation: "Modifies an existing database object (table, procedure, trigger, etc.)." },
  { label: "AND", detail: "Firebird reserved word", documentation: "Logical AND operator for combining conditions." },
  { label: "ANY", detail: "Firebird reserved word", documentation: "Compares a value to any value in a subquery result." },
  { label: "AS", detail: "Firebird reserved word", documentation: "Assigns an alias to a table, column, or expression." },
  { label: "AT", detail: "Firebird reserved word", documentation: "Used in time zone expressions." },
  { label: "AVG", detail: "Firebird aggregate function", documentation: "Returns the average value of a numeric column.\n\nSyntax: `AVG([ALL | DISTINCT] expression)`" },
  { label: "BEGIN", detail: "Firebird PSQL keyword", documentation: "Starts a PSQL block (procedure/trigger body or EXECUTE BLOCK)." },
  { label: "BETWEEN", detail: "Firebird reserved word", documentation: "Selects values within a given range (inclusive).\n\nSyntax: `expr BETWEEN low AND high`" },
  { label: "BIGINT", detail: "Firebird data type", documentation: "64-bit signed integer data type. Range: -2^63 to 2^63 - 1." },
  { label: "BIT_LENGTH", detail: "Firebird function", documentation: "Returns the length of a string in bits.\n\nSyntax: `BIT_LENGTH(string)`" },
  { label: "BLOB", detail: "Firebird data type", documentation: "Binary Large Object for storing large data (text or binary)." },
  { label: "BOTH", detail: "Firebird reserved word", documentation: "Used with TRIM to remove characters from both sides." },
  { label: "BY", detail: "Firebird reserved word", documentation: "Used with GROUP BY, ORDER BY, and PARTITION BY clauses." },
  { label: "CASE", detail: "Firebird reserved word", documentation: "Conditional expression (simple or searched form).\n\nSyntax: `CASE WHEN condition THEN result [ELSE default] END`" },
  { label: "CAST", detail: "Firebird function", documentation: "Converts a value to a specified data type.\n\nSyntax: `CAST(value AS data_type)`" },
  { label: "CHAR", detail: "Firebird data type", documentation: "Fixed-length character string data type." },
  { label: "CHAR_LENGTH", detail: "Firebird function", documentation: "Returns the number of characters in a string.\n\nSyntax: `CHAR_LENGTH(string)`" },
  { label: "CHARACTER", detail: "Firebird data type", documentation: "Synonym for CHAR data type." },
  { label: "CHARACTER_LENGTH", detail: "Firebird function", documentation: "Returns the number of characters in a string.\n\nSyntax: `CHARACTER_LENGTH(string)`" },
  { label: "CHECK", detail: "Firebird reserved word", documentation: "Defines a constraint that limits column values." },
  { label: "CLOSE", detail: "Firebird PSQL keyword", documentation: "Closes a previously opened cursor." },
  { label: "COLLATE", detail: "Firebird reserved word", documentation: "Specifies the collation order for a character column." },
  { label: "COLUMN", detail: "Firebird reserved word", documentation: "Refers to a table column in DDL statements." },
  { label: "COMMIT", detail: "Firebird reserved word", documentation: "Commits the current transaction, making changes permanent." },
  { label: "CONNECT", detail: "Firebird reserved word", documentation: "Establishes a connection to a database." },
  { label: "CONSTRAINT", detail: "Firebird reserved word", documentation: "Defines a constraint on a table (PRIMARY KEY, FOREIGN KEY, CHECK, UNIQUE)." },
  { label: "COUNT", detail: "Firebird aggregate function", documentation: "Returns the number of rows matching a condition.\n\nSyntax: `COUNT([ALL | DISTINCT] expression)` or `COUNT(*)`" },
  { label: "CREATE", detail: "Firebird reserved word", documentation: "Creates a new database object (table, view, procedure, trigger, etc.)." },
  { label: "CROSS", detail: "Firebird reserved word", documentation: "Cross join — produces the Cartesian product of two tables." },
  { label: "CURRENT", detail: "Firebird reserved word", documentation: "Used in cursor operations to reference the current row." },
  { label: "CURRENT_CONNECTION", detail: "Firebird context variable", documentation: "Returns the unique identifier of the current connection." },
  { label: "CURRENT_DATE", detail: "Firebird context variable", documentation: "Returns the current date (server-side)." },
  { label: "CURRENT_ROLE", detail: "Firebird context variable", documentation: "Returns the current role of the user." },
  { label: "CURRENT_TIME", detail: "Firebird context variable", documentation: "Returns the current time (server-side)." },
  { label: "CURRENT_TIMESTAMP", detail: "Firebird context variable", documentation: "Returns the current date and time (server-side)." },
  { label: "CURRENT_TRANSACTION", detail: "Firebird context variable", documentation: "Returns the unique identifier of the current transaction." },
  { label: "CURRENT_USER", detail: "Firebird context variable", documentation: "Returns the name of the currently authenticated user." },
  { label: "CURSOR", detail: "Firebird PSQL keyword", documentation: "Declares a named cursor for row-by-row processing in PSQL." },
  { label: "DATE", detail: "Firebird data type", documentation: "Stores a calendar date (year, month, day)." },
  { label: "DAY", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT and interval expressions." },
  { label: "DEC", detail: "Firebird data type", documentation: "Synonym for DECIMAL data type." },
  { label: "DECIMAL", detail: "Firebird data type", documentation: "Exact numeric data type with fixed precision and scale.\n\nSyntax: `DECIMAL(precision, scale)`" },
  { label: "DECLARE", detail: "Firebird PSQL keyword", documentation: "Declares a local variable or cursor in a PSQL block.\n\nSyntax: `DECLARE VARIABLE name type;`" },
  { label: "DEFAULT", detail: "Firebird reserved word", documentation: "Specifies a default value for a column." },
  { label: "DELETE", detail: "Firebird reserved word", documentation: "Removes rows from a table.\n\nSyntax: `DELETE FROM table [WHERE condition]`" },
  { label: "DISCONNECT", detail: "Firebird reserved word", documentation: "Disconnects from a database." },
  { label: "DISTINCT", detail: "Firebird reserved word", documentation: "Eliminates duplicate rows from a result set." },
  { label: "DOUBLE", detail: "Firebird data type", documentation: "Double-precision floating-point number (DOUBLE PRECISION)." },
  { label: "DROP", detail: "Firebird reserved word", documentation: "Removes a database object (table, view, procedure, trigger, etc.)." },
  { label: "ELSE", detail: "Firebird reserved word", documentation: "Specifies the alternative in IF/CASE statements." },
  { label: "END", detail: "Firebird PSQL keyword", documentation: "Ends a PSQL block (BEGIN...END)." },
  { label: "ESCAPE", detail: "Firebird reserved word", documentation: "Defines an escape character for LIKE patterns." },
  { label: "EXCEPTION", detail: "Firebird PSQL keyword", documentation: "Raises a user-defined exception in PSQL.\n\nSyntax: `EXCEPTION exception_name [message];`" },
  { label: "EXECUTE", detail: "Firebird reserved word", documentation: "Executes a stored procedure or dynamic SQL statement." },
  { label: "EXISTS", detail: "Firebird reserved word", documentation: "Tests for the existence of rows in a subquery.\n\nSyntax: `EXISTS (subquery)`" },
  { label: "EXIT", detail: "Firebird PSQL keyword", documentation: "Exits the current PSQL procedure, returning control to the caller." },
  { label: "EXTERNAL", detail: "Firebird reserved word", documentation: "Declares an external function or procedure (UDF)." },
  { label: "EXTRACT", detail: "Firebird function", documentation: "Extracts a part from a date/time value.\n\nSyntax: `EXTRACT(part FROM datetime)`\n\nParts: YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND, WEEK, WEEKDAY, YEARDAY" },
  { label: "FETCH", detail: "Firebird PSQL keyword", documentation: "Fetches the next row from a cursor." },
  { label: "FILTER", detail: "Firebird reserved word", documentation: "Filters rows for aggregate functions.\n\nSyntax: `aggregate_function(...) FILTER (WHERE condition)`" },
  { label: "FIRST", detail: "Firebird keyword", documentation: "Limits the number of rows returned.\n\nSyntax: `SELECT FIRST n ... FROM table`" },
  { label: "FLOAT", detail: "Firebird data type", documentation: "Single-precision floating-point number data type." },
  { label: "FOR", detail: "Firebird PSQL keyword", documentation: "Used in FOR SELECT...DO loops in PSQL." },
  { label: "FOREIGN", detail: "Firebird reserved word", documentation: "Defines a foreign key constraint referencing another table." },
  { label: "FROM", detail: "Firebird reserved word", documentation: "Specifies the source table(s) in a query." },
  { label: "FULL", detail: "Firebird reserved word", documentation: "Full outer join — returns all rows from both tables." },
  { label: "FUNCTION", detail: "Firebird reserved word", documentation: "Declares a stored function (Firebird 3.0+)." },
  { label: "GDSCODE", detail: "Firebird PSQL keyword", documentation: "References a Firebird error code in WHEN...DO exception handling." },
  { label: "GLOBAL", detail: "Firebird reserved word", documentation: "Used with global temporary tables." },
  { label: "GRANT", detail: "Firebird reserved word", documentation: "Grants privileges to users or roles." },
  { label: "GROUP", detail: "Firebird reserved word", documentation: "Groups rows that share values for aggregate functions.\n\nSyntax: `GROUP BY column1 [, column2, ...]`" },
  { label: "HAVING", detail: "Firebird reserved word", documentation: "Filters groups in a GROUP BY clause.\n\nSyntax: `HAVING condition`" },
  { label: "HOUR", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT." },
  { label: "IF", detail: "Firebird PSQL keyword", documentation: "Conditional execution in PSQL blocks.\n\nSyntax: `IF (condition) THEN statement [ELSE statement]`" },
  { label: "IN", detail: "Firebird reserved word", documentation: "Tests if a value is in a list or subquery.\n\nSyntax: `expr IN (value1, value2, ...)` or `expr IN (subquery)`" },
  { label: "INDEX", detail: "Firebird reserved word", documentation: "Creates or references a database index." },
  { label: "INNER", detail: "Firebird reserved word", documentation: "Inner join — returns only matching rows from both tables." },
  { label: "INPUT_TYPE", detail: "Firebird PSQL keyword", documentation: "Specifies input parameter type for stored procedures." },
  { label: "INSENSITIVE", detail: "Firebird reserved word", documentation: "Specifies an insensitive cursor." },
  { label: "INSERT", detail: "Firebird reserved word", documentation: "Inserts new rows into a table.\n\nSyntax: `INSERT INTO table (columns) VALUES (values)`" },
  { label: "INT", detail: "Firebird data type", documentation: "Synonym for INTEGER data type." },
  { label: "INTEGER", detail: "Firebird data type", documentation: "32-bit signed integer data type." },
  { label: "INTO", detail: "Firebird reserved word", documentation: "Specifies the target in INSERT or the destination in SELECT...INTO." },
  { label: "IS", detail: "Firebird reserved word", documentation: "Used in IS NULL, IS NOT NULL comparisons." },
  { label: "JOIN", detail: "Firebird reserved word", documentation: "Combines rows from two or more tables based on a related column." },
  { label: "LEADING", detail: "Firebird reserved word", documentation: "Used with TRIM to remove leading characters." },
  { label: "LEAVE", detail: "Firebird PSQL keyword", documentation: "Exits the current WHILE or FOR loop in PSQL." },
  { label: "LEFT", detail: "Firebird reserved word", documentation: "Left outer join — returns all rows from the left table." },
  { label: "LIKE", detail: "Firebird reserved word", documentation: "Pattern matching with wildcards (% and _).\n\nSyntax: `expr LIKE pattern [ESCAPE char]`" },
  { label: "LONG", detail: "Firebird data type", documentation: "Long integer data type." },
  { label: "LOWER", detail: "Firebird function", documentation: "Converts a string to lowercase.\n\nSyntax: `LOWER(string)`" },
  { label: "MAX", detail: "Firebird aggregate function", documentation: "Returns the maximum value in a set.\n\nSyntax: `MAX([ALL | DISTINCT] expression)`" },
  { label: "MAXIMUM_SEGMENT", detail: "Firebird reserved word", documentation: "Specifies the maximum segment size for BLOB columns." },
  { label: "MERGE", detail: "Firebird reserved word", documentation: "Performs INSERT, UPDATE, or DELETE based on matching conditions.\n\nSyntax: `MERGE INTO target USING source ON condition WHEN MATCHED/NOT MATCHED ...`" },
  { label: "MIN", detail: "Firebird aggregate function", documentation: "Returns the minimum value in a set.\n\nSyntax: `MIN([ALL | DISTINCT] expression)`" },
  { label: "MINUTE", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT." },
  { label: "MONTH", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT." },
  { label: "NATIONAL", detail: "Firebird reserved word", documentation: "National character set prefix for character types." },
  { label: "NATURAL", detail: "Firebird reserved word", documentation: "Natural join — joins tables on all common column names." },
  { label: "NCHAR", detail: "Firebird data type", documentation: "National character data type." },
  { label: "NEW", detail: "Firebird PSQL keyword", documentation: "References the new row values in a trigger context (AFTER INSERT, AFTER UPDATE)." },
  { label: "NO", detail: "Firebird reserved word", documentation: "Negation keyword used in various contexts." },
  { label: "NOT", detail: "Firebird reserved word", documentation: "Logical NOT operator." },
  { label: "NULL", detail: "Firebird reserved word", documentation: "Represents an unknown or missing value." },
  { label: "NUMERIC", detail: "Firebird data type", documentation: "Exact numeric data type.\n\nSyntax: `NUMERIC(precision, scale)`" },
  { label: "OCTET_LENGTH", detail: "Firebird function", documentation: "Returns the length of a string in bytes.\n\nSyntax: `OCTET_LENGTH(string)`" },
  { label: "OF", detail: "Firebird reserved word", documentation: "Used in various clauses." },
  { label: "OLD", detail: "Firebird PSQL keyword", documentation: "References the old row values in a trigger context (BEFORE UPDATE, BEFORE DELETE)." },
  { label: "ON", detail: "Firebird reserved word", documentation: "Specifies the join condition or trigger event." },
  { label: "ONLY", detail: "Firebird reserved word", documentation: "Used with FETCH/OFFSET row limiting." },
  { label: "OPEN", detail: "Firebird PSQL keyword", documentation: "Opens a previously declared cursor." },
  { label: "OR", detail: "Firebird reserved word", documentation: "Logical OR operator for combining conditions." },
  { label: "ORDER", detail: "Firebird reserved word", documentation: "Sorts the result set.\n\nSyntax: `ORDER BY column [ASC | DESC]`" },
  { label: "OUTER", detail: "Firebird reserved word", documentation: "Specifies an outer join (LEFT, RIGHT, or FULL)." },
  { label: "OUTPUT_TYPE", detail: "Firebird PSQL keyword", documentation: "Specifies output parameter type for stored procedures." },
  { label: "PARAMETER", detail: "Firebird reserved word", documentation: "Declares a parameter in a stored procedure." },
  { label: "PLAN", detail: "Firebird reserved word", documentation: "Specifies a manual query plan.\n\nSyntax: `PLAN (table_name NATURAL | INDEX (index_name))`" },
  { label: "POSITION", detail: "Firebird function", documentation: "Returns the position of a substring within a string.\n\nSyntax: `POSITION(substring IN string)`" },
  { label: "POST_EVENT", detail: "Firebird PSQL keyword", documentation: "Posts a database event for notification.\n\nSyntax: `POST_EVENT event_name;`" },
  { label: "PRECISION", detail: "Firebird reserved word", documentation: "Specifies the precision for numeric types." },
  { label: "PRIMARY", detail: "Firebird reserved word", documentation: "Defines a primary key constraint." },
  { label: "PROCEDURE", detail: "Firebird reserved word", documentation: "Declares a stored procedure." },
  { label: "RDB$DB_KEY", detail: "Firebird reserved word", documentation: "Internal row identifier (pseudo-column)." },
  { label: "REAL", detail: "Firebird data type", documentation: "Single-precision floating-point data type." },
  { label: "RECORD_VERSION", detail: "Firebird reserved word", documentation: "Record version for optimistic concurrency control." },
  { label: "RECREATE", detail: "Firebird reserved word", documentation: "Drops and recreates a database object if it exists." },
  { label: "RECURSIVE", detail: "Firebird reserved word", documentation: "Used with recursive common table expressions (WITH RECURSIVE)." },
  { label: "REFERENCES", detail: "Firebird reserved word", documentation: "Specifies the referenced table in a FOREIGN KEY constraint." },
  { label: "RELEASE", detail: "Firebird reserved word", documentation: "Releases a savepoint.\n\nSyntax: `RELEASE SAVEPOINT name`" },
  { label: "RETURNING", detail: "Firebird reserved word", documentation: "Returns values from INSERT, UPDATE, or DELETE statements.\n\nSyntax: `INSERT INTO ... VALUES (...) RETURNING column1, column2`" },
  { label: "RETURNING_VALUES", detail: "Firebird PSQL keyword", documentation: "Returns values from an EXECUTE PROCEDURE call in PSQL." },
  { label: "RETURNS", detail: "Firebird PSQL keyword", documentation: "Declares the output parameters of a stored procedure.\n\nSyntax: `RETURNS (param1 type, param2 type)`" },
  { label: "REVOKE", detail: "Firebird reserved word", documentation: "Revokes privileges from users or roles." },
  { label: "RIGHT", detail: "Firebird reserved word", documentation: "Right outer join — returns all rows from the right table." },
  { label: "ROLLBACK", detail: "Firebird reserved word", documentation: "Rolls back the current transaction." },
  { label: "ROW_COUNT", detail: "Firebird PSQL context variable", documentation: "Returns the number of rows affected by the last DML statement in PSQL." },
  { label: "ROWS", detail: "Firebird reserved word", documentation: "Limits result rows.\n\nSyntax: `ROWS m TO n`" },
  { label: "SAVEPOINT", detail: "Firebird reserved word", documentation: "Creates a savepoint within a transaction.\n\nSyntax: `SAVEPOINT name`" },
  { label: "SECOND", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT." },
  { label: "SELECT", detail: "Firebird reserved word", documentation: "Retrieves data from one or more tables.\n\nSyntax: `SELECT columns FROM table [WHERE condition] [ORDER BY column]`" },
  { label: "SENSITIVE", detail: "Firebird reserved word", documentation: "Specifies a sensitive cursor." },
  { label: "SET", detail: "Firebird reserved word", documentation: "Used in UPDATE SET and SET TERM statements." },
  { label: "SIMILAR", detail: "Firebird reserved word", documentation: "Regular expression pattern matching.\n\nSyntax: `expr SIMILAR TO pattern`" },
  { label: "SKIP", detail: "Firebird keyword", documentation: "Skips a number of rows before returning results.\n\nSyntax: `SELECT FIRST n SKIP m ... FROM table`" },
  { label: "SMALLINT", detail: "Firebird data type", documentation: "16-bit signed integer data type. Range: -32,768 to 32,767." },
  { label: "SOME", detail: "Firebird reserved word", documentation: "Synonym for ANY in subquery comparisons." },
  { label: "SQLCODE", detail: "Firebird PSQL keyword", documentation: "References SQL error codes in WHEN...DO exception handling." },
  { label: "SQLSTATE", detail: "Firebird PSQL keyword", documentation: "References SQL state codes in WHEN...DO exception handling." },
  { label: "START", detail: "Firebird reserved word", documentation: "Used with START TRANSACTION or START WITH." },
  { label: "SUM", detail: "Firebird aggregate function", documentation: "Returns the sum of values in a set.\n\nSyntax: `SUM([ALL | DISTINCT] expression)`" },
  { label: "SUSPEND", detail: "Firebird PSQL keyword", documentation: "Suspends execution of a selectable procedure and returns the current output row." },
  { label: "TABLE", detail: "Firebird reserved word", documentation: "Declares a database table." },
  { label: "THEN", detail: "Firebird reserved word", documentation: "Specifies the result in IF/CASE/WHEN expressions." },
  { label: "TIME", detail: "Firebird data type", documentation: "Stores a time of day (hours, minutes, seconds)." },
  { label: "TIMESTAMP", detail: "Firebird data type", documentation: "Stores both date and time." },
  { label: "TO", detail: "Firebird reserved word", documentation: "Used in CAST, ROWS, and range expressions." },
  { label: "TRAILING", detail: "Firebird reserved word", documentation: "Used with TRIM to remove trailing characters." },
  { label: "TRIGGER", detail: "Firebird reserved word", documentation: "Declares a database trigger." },
  { label: "TRIM", detail: "Firebird function", documentation: "Removes leading/trailing characters from a string.\n\nSyntax: `TRIM([LEADING|TRAILING|BOTH] [char] FROM string)`" },
  { label: "UNION", detail: "Firebird reserved word", documentation: "Combines result sets from two or more SELECT statements." },
  { label: "UNIQUE", detail: "Firebird reserved word", documentation: "Defines a unique constraint on a column or index." },
  { label: "UPDATE", detail: "Firebird reserved word", documentation: "Modifies existing rows in a table.\n\nSyntax: `UPDATE table SET column = value [WHERE condition]`" },
  { label: "UPPER", detail: "Firebird function", documentation: "Converts a string to uppercase.\n\nSyntax: `UPPER(string)`" },
  { label: "USER", detail: "Firebird reserved word", documentation: "References the current user." },
  { label: "USING", detail: "Firebird reserved word", documentation: "Specifies join columns or input parameters." },
  { label: "VALUE", detail: "Firebird reserved word", documentation: "Used in domain CHECK constraints to reference the value being checked." },
  { label: "VALUES", detail: "Firebird reserved word", documentation: "Specifies values for INSERT statements." },
  { label: "VARCHAR", detail: "Firebird data type", documentation: "Variable-length character string.\n\nSyntax: `VARCHAR(length)`" },
  { label: "VARIABLE", detail: "Firebird PSQL keyword", documentation: "Used with DECLARE VARIABLE to declare local variables." },
  { label: "VARYING", detail: "Firebird reserved word", documentation: "Alternative syntax for VARCHAR (CHARACTER VARYING)." },
  { label: "VIEW", detail: "Firebird reserved word", documentation: "Declares a database view." },
  { label: "WHEN", detail: "Firebird reserved word", documentation: "Specifies a condition in CASE or exception handling (WHEN...DO in PSQL)." },
  { label: "WHERE", detail: "Firebird reserved word", documentation: "Filters rows in a query.\n\nSyntax: `WHERE condition`" },
  { label: "WHILE", detail: "Firebird PSQL keyword", documentation: "Loop construct in PSQL.\n\nSyntax: `WHILE (condition) DO statement`" },
  { label: "WITH", detail: "Firebird reserved word", documentation: "Defines Common Table Expressions (CTEs).\n\nSyntax: `WITH cte_name AS (SELECT ...) SELECT ... FROM cte_name`" },
  { label: "YEAR", detail: "Firebird reserved word", documentation: "Date/time part used with EXTRACT." }
];

/**
 * Firebird PSQL-specific keywords for procedural SQL blocks
 */
export const firebirdPsqlKeywords: FirebirdReserved[] = [
  { label: "EXECUTE BLOCK", detail: "Firebird PSQL", documentation: "Executes an anonymous PSQL block.\n\nSyntax:\n```sql\nEXECUTE BLOCK\nAS\nBEGIN\n  /* statements */\nEND\n```" },
  { label: "EXECUTE PROCEDURE", detail: "Firebird PSQL", documentation: "Calls a stored procedure.\n\nSyntax: `EXECUTE PROCEDURE proc_name [param1, param2, ...]`" },
  { label: "EXECUTE STATEMENT", detail: "Firebird PSQL", documentation: "Executes a dynamic SQL string in PSQL.\n\nSyntax: `EXECUTE STATEMENT sql_string`" },
  { label: "FOR SELECT", detail: "Firebird PSQL", documentation: "Iterates over a SELECT result set in PSQL.\n\nSyntax:\n```sql\nFOR SELECT columns FROM table INTO :variables DO\nBEGIN\n  /* statements */\nEND\n```" },
  { label: "DECLARE VARIABLE", detail: "Firebird PSQL", documentation: "Declares a local variable in a PSQL block.\n\nSyntax: `DECLARE VARIABLE var_name data_type [= default_value];`" },
  { label: "DECLARE CURSOR", detail: "Firebird PSQL", documentation: "Declares a named cursor in a PSQL block.\n\nSyntax: `DECLARE cursor_name CURSOR FOR (SELECT ...);`" },
  { label: "SET TERM", detail: "Firebird DDL", documentation: "Changes the statement terminator in isql scripts.\n\nSyntax: `SET TERM new_term old_term`\n\nExample: `SET TERM ^ ;`" },
  { label: "IN AUTONOMOUS TRANSACTION", detail: "Firebird PSQL", documentation: "Executes statements in an independent transaction.\n\nSyntax:\n```sql\nIN AUTONOMOUS TRANSACTION DO\nBEGIN\n  /* statements */\nEND\n```" },
  { label: "WHEN ANY DO", detail: "Firebird PSQL", documentation: "Catches any exception in a PSQL block.\n\nSyntax:\n```sql\nBEGIN\n  /* statements */\nWHEN ANY DO\nBEGIN\n  /* error handling */\nEND\nEND\n```" },
  { label: "WHEN GDSCODE", detail: "Firebird PSQL", documentation: "Catches a specific Firebird error by GDS code.\n\nSyntax: `WHEN GDSCODE error_name DO ...`" },
  { label: "WHEN SQLCODE", detail: "Firebird PSQL", documentation: "Catches a specific SQL error code.\n\nSyntax: `WHEN SQLCODE code DO ...`" },
  { label: "WHEN EXCEPTION", detail: "Firebird PSQL", documentation: "Catches a user-defined exception.\n\nSyntax: `WHEN EXCEPTION exc_name DO ...`" },
];

/**
 * Firebird built-in scalar and aggregate functions
 */
export const firebirdBuiltinFunctions: FirebirdReserved[] = [
  { label: "ABS", detail: "Firebird function", documentation: "Returns the absolute value of a number.\n\nSyntax: `ABS(number)`" },
  { label: "ACOS", detail: "Firebird function", documentation: "Returns the arc cosine.\n\nSyntax: `ACOS(number)`" },
  { label: "ASIN", detail: "Firebird function", documentation: "Returns the arc sine.\n\nSyntax: `ASIN(number)`" },
  { label: "ATAN", detail: "Firebird function", documentation: "Returns the arc tangent.\n\nSyntax: `ATAN(number)`" },
  { label: "ATAN2", detail: "Firebird function", documentation: "Returns the arc tangent of y/x.\n\nSyntax: `ATAN2(y, x)`" },
  { label: "CEILING", detail: "Firebird function", documentation: "Rounds a number up to the nearest integer.\n\nSyntax: `CEILING(number)`" },
  { label: "COALESCE", detail: "Firebird function", documentation: "Returns the first non-NULL value from a list.\n\nSyntax: `COALESCE(value1, value2, ...)`" },
  { label: "COS", detail: "Firebird function", documentation: "Returns the cosine.\n\nSyntax: `COS(angle)`" },
  { label: "COSH", detail: "Firebird function", documentation: "Returns the hyperbolic cosine.\n\nSyntax: `COSH(number)`" },
  { label: "EXP", detail: "Firebird function", documentation: "Returns e raised to the given power.\n\nSyntax: `EXP(number)`" },
  { label: "FLOOR", detail: "Firebird function", documentation: "Rounds a number down to the nearest integer.\n\nSyntax: `FLOOR(number)`" },
  { label: "GEN_ID", detail: "Firebird function", documentation: "Generates the next value from a generator/sequence.\n\nSyntax: `GEN_ID(generator_name, increment)`" },
  { label: "GEN_UUID", detail: "Firebird function", documentation: "Generates a universally unique identifier (UUID).\n\nSyntax: `GEN_UUID()`" },
  { label: "HASH", detail: "Firebird function", documentation: "Returns a hash value of the argument.\n\nSyntax: `HASH(value)`" },
  { label: "IIF", detail: "Firebird function", documentation: "Inline IF — returns one of two values based on a condition.\n\nSyntax: `IIF(condition, value_if_true, value_if_false)`" },
  { label: "LEFT", detail: "Firebird function", documentation: "Returns the leftmost characters of a string.\n\nSyntax: `LEFT(string, length)`" },
  { label: "LN", detail: "Firebird function", documentation: "Returns the natural logarithm.\n\nSyntax: `LN(number)`" },
  { label: "LOG", detail: "Firebird function", documentation: "Returns the logarithm of a number to the specified base.\n\nSyntax: `LOG(base, number)`" },
  { label: "LOG10", detail: "Firebird function", documentation: "Returns the base-10 logarithm.\n\nSyntax: `LOG10(number)`" },
  { label: "LPAD", detail: "Firebird function", documentation: "Left-pads a string to a specified length.\n\nSyntax: `LPAD(string, length [, pad_string])`" },
  { label: "MAXVALUE", detail: "Firebird function", documentation: "Returns the maximum value from a list.\n\nSyntax: `MAXVALUE(value1, value2, ...)`" },
  { label: "MINVALUE", detail: "Firebird function", documentation: "Returns the minimum value from a list.\n\nSyntax: `MINVALUE(value1, value2, ...)`" },
  { label: "MOD", detail: "Firebird function", documentation: "Returns the remainder of integer division.\n\nSyntax: `MOD(number, divisor)`" },
  { label: "NULLIF", detail: "Firebird function", documentation: "Returns NULL if two values are equal, otherwise returns the first value.\n\nSyntax: `NULLIF(value1, value2)`" },
  { label: "OVERLAY", detail: "Firebird function", documentation: "Replaces part of a string with another string.\n\nSyntax: `OVERLAY(string PLACING replacement FROM start [FOR length])`" },
  { label: "PI", detail: "Firebird function", documentation: "Returns the value of π (pi).\n\nSyntax: `PI()`" },
  { label: "POWER", detail: "Firebird function", documentation: "Returns a number raised to a power.\n\nSyntax: `POWER(base, exponent)`" },
  { label: "RAND", detail: "Firebird function", documentation: "Returns a random number between 0 and 1.\n\nSyntax: `RAND()`" },
  { label: "REPLACE", detail: "Firebird function", documentation: "Replaces all occurrences of a substring.\n\nSyntax: `REPLACE(string, search, replacement)`" },
  { label: "REVERSE", detail: "Firebird function", documentation: "Reverses a string.\n\nSyntax: `REVERSE(string)`" },
  { label: "RIGHT", detail: "Firebird function", documentation: "Returns the rightmost characters of a string.\n\nSyntax: `RIGHT(string, length)`" },
  { label: "ROUND", detail: "Firebird function", documentation: "Rounds a number to a specified number of decimal places.\n\nSyntax: `ROUND(number [, scale])`" },
  { label: "RPAD", detail: "Firebird function", documentation: "Right-pads a string to a specified length.\n\nSyntax: `RPAD(string, length [, pad_string])`" },
  { label: "SIGN", detail: "Firebird function", documentation: "Returns -1, 0, or 1 depending on the sign of the number.\n\nSyntax: `SIGN(number)`" },
  { label: "SIN", detail: "Firebird function", documentation: "Returns the sine.\n\nSyntax: `SIN(angle)`" },
  { label: "SINH", detail: "Firebird function", documentation: "Returns the hyperbolic sine.\n\nSyntax: `SINH(number)`" },
  { label: "SQRT", detail: "Firebird function", documentation: "Returns the square root of a number.\n\nSyntax: `SQRT(number)`" },
  { label: "SUBSTRING", detail: "Firebird function", documentation: "Extracts a substring from a string.\n\nSyntax: `SUBSTRING(string FROM start [FOR length])`" },
  { label: "TAN", detail: "Firebird function", documentation: "Returns the tangent.\n\nSyntax: `TAN(angle)`" },
  { label: "TANH", detail: "Firebird function", documentation: "Returns the hyperbolic tangent.\n\nSyntax: `TANH(number)`" },
  { label: "TRUNC", detail: "Firebird function", documentation: "Truncates a number to a specified number of decimal places.\n\nSyntax: `TRUNC(number [, scale])`" },
  { label: "LIST", detail: "Firebird aggregate function", documentation: "Concatenates values from multiple rows into a delimited string.\n\nSyntax: `LIST([ALL | DISTINCT] expression [, delimiter])`" },
];
